# plot.py

# Script to visualize the quality of the algorithms.

# Loads results from a .pkl file (generated by main.py), computes the average approximation ratio (ALG / OPT)
# for different values of n (number of items), and plots the ratio (and other metrics) with error bars.
# The plot helps evaluate how the performance of the algorithms scales with problem size.

# Plots are currently generated without titles (titles were added manually in LaTeX later). If you want titles,
# uncomment the relevant lines.

import math
import numpy as np
import os
import matplotlib
import matplotlib.pyplot as plt

# Global matplotlib settings for consistent styling
matplotlib.rcParams.update({
    "text.usetex": True,
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica"],
    "axes.labelsize": 17,
    "font.size": 17,
    "legend.fontsize": 17,
    "xtick.labelsize": 17,
    "ytick.labelsize": 17,
    "grid.linestyle": ":",
    "grid.linewidth": 0.5,
    "grid.alpha": 0.4,
    "axes.grid": True,
    "figure.figsize": (20, 6) # 10 in when legend in fiigure
})

matplotlib.rcParams["text.latex.preamble"] = r"""
\usepackage[T1]{fontenc}
\usepackage{helvet}
\usepackage{sansmath}
\sansmath
"""


COL = {
    "primal": "#000000",
    "primal_dual": "#000000",
    "dual": "#008800",
    "midpoint": "#778899",
    "worst_case_p_item": "#778899",
    "opt_w": "#2E8B57",
    "opt_w_remember": "#007700",
    "opt_w_n_remember": "#0055AA",
    "opt_w_n_remember_rob_obj": "#663399",
    "solve_two_branches_smallest_wi": "#770000",
    "solve_two_branches_biggest_wi": "#AA5500",
    "primal_branching": "#778800",
    "doerr_rr": "#550011"
}


STYLE = {
    "primal":            dict(linestyle="-",  marker="o"),
    "primal_dual":       dict(linestyle="--", marker="s"),
    "dual":              dict(linestyle=":",  marker="v"),
    "midpoint":          dict(linestyle="-.", marker="D"),
    "worst_case_p_item": dict(linestyle=":",  marker="^"),
    "opt_w":             dict(linestyle="--", marker="x"),
    "opt_w_remember":    dict(linestyle="--", marker=">"),
    "opt_w_n_remember":  dict(linestyle="-",  marker="^"),
    "opt_w_n_remember_rob_obj": dict(linestyle="--", marker="p"),
    "solve_two_branches_smallest_wi": dict(linestyle="--", marker="<"),
    "solve_two_branches_biggest_wi": dict(linestyle="-", marker="v"),
    "primal_branching": dict(linestyle=":", marker="v"),
    "doerr_rr": dict(linestyle="-",  marker="o"),
}



def _finite(arr):
    a = np.asarray(arr, dtype=float)
    return a[np.isfinite(a)]


def safe_mean(values):
    vals = _finite(values)
    if vals.size == 0:
        return math.nan
    return float(np.mean(vals))


def safe_ci95(values):
    vals = _finite(values)
    sample_size = vals.size
    if sample_size < 2:
        return 0.0
    return 1.98 * float(np.std(vals, ddof=1)) / math.sqrt(sample_size)


def plot_approx_ratio_only(all_results, num_runs, var_param, fixed_n=None, fixed_k=None, c_range=None,
                           output_dir="results"):
    param_suffix = f"_{var_param}" if var_param in {"n", "k", "p"} else ""
    output_plot = f"{output_dir}/plot_approx_ratio_only_{param_suffix}.png"
    if not all_results:
        print("No results to plot.")
        return
    alg_key = all_results[0].get("algorithm", "") if all_results else ""
    label_map = {
        "primal": r"Primal rounding",
        "primal_dual": r"Primal-dual rounding",
        "dual": r"Dual approach",
        "midpoint": r"Midpoint method",
        "worst_case_p_item": r"Worst-case-per-item",
        "opt_w": r"Solve LP select smallest p",
        "opt_w_remember": r"Solve LP p times select iteratively",
        "opt_w_n_remember": r"Solve LP n times each step",
        "opt_w_n_remember_rob_obj": r"Solve LP n times each step (remember, min robust obj)",
        "solve_two_branches_smallest_wi": r"Solve LP pick smallest wi - branch",
        "solve_two_branches_biggest_wi": r"Solve LP pick biggest wi - branch",
        "primal_branching": r"Primal Rounding - branch",
        "doerr_rr": r"Randomized Rounding",
    }
    base_label = label_map.get(alg_key, alg_key)
    method_label = rf"{base_label} $\mathrm{{ALG}} / \mathrm{{OPT}}_\mathrm{{IP}}$"
    color_line = COL.get(alg_key, "tab:gray")
    style = STYLE.get(alg_key, dict(linestyle="-", marker="o"))

    # Organize data by varying parameter (n, k, p)
    param_to_ratios = {}
    for entry in all_results:
        param = entry["varying_param"]
        ratio = entry["ratio_alg_opt"]
        param_to_ratios.setdefault(param, []).append(ratio)

    # Prepare data for plotting
    param_values = sorted(param_to_ratios.keys())
    avg_ratios = [safe_mean(param_to_ratios[param]) for param in param_values]
    ci_ratios_95 = [safe_ci95(param_to_ratios[param]) for param in param_values]
    fig = plt.figure()
    # Plot
    plt.errorbar(param_values, avg_ratios, yerr=ci_ratios_95, fmt='-o', capsize=5,
                 label=rf"{method_label} (Ø $\pm$ 95\% CI)", color=color_line)
    xlabel_map = {
        "n": r"Number of items $n$",
        "k": r"Number of scenarios $k$",
        "p": r"Number of items to select $p$"
    }
    plt.xlabel(xlabel_map.get(var_param, ""))
    plt.ylabel(r"Approximation ratio")
    # main_title = f"Primal Rounding Approximation Ratio {titles[criterion]} criterion"
    p_label = all_results[0]["p_label"] if all_results and "p_label" in all_results[0] else ""
    subtitle = (
            r"(Average over " + str(num_runs) + r" runs $\mid$ "
            + (r"$n$=" + str(fixed_n) + ", " if var_param != "n" and fixed_n is not None else "")
            + (r"$p$=" + p_label + ", " if var_param != "p" and p_label else "")
            + (r"$k$=" + str(fixed_k) + ", " if var_param != "k" and fixed_k is not None else "")
            + r"cost range: [1, " + str(c_range) + "])"
    )
    # plt.title(f"{main_title}\n{subtitle}")
    plt.title(subtitle)
    plt.xticks(param_values)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_plot, bbox_inches='tight')
    plt.close(fig)
    print(f"Plot saved to {output_plot}")


def plot_ratio_comp(results_by_alg, num_runs, var_param, fixed_n=None, fixed_k=None, c_range=None,
                    output_dir="results"):

    param_suffix = f"_{var_param}" if var_param in {"n", "k", "p"} else ""
    output_plot = f"{output_dir}/plot_ratio_comparison{param_suffix}.png"

    if not results_by_alg:
        print("No results to compare.")
        return

    label_map = {
        "primal": r"Primal rounding",
        "primal_dual": r"Primal-dual rounding",
        "dual": r"Dual approach",
        "midpoint": r"Midpoint method",
        "worst_case_p_item": r"Worst-case-per-item",
        "opt_w": r"Solve LP select smallest p",
        "opt_w_remember": r"Solve LP p times select iteratively (remember)",
        "opt_w_n_remember": r"Solve LP n times each step (remember)",
        "opt_w_n_remember_rob_obj": r"Solve LP n times each step (remember, min robust obj)",
        "solve_two_branches_smallest_wi": r"Solve LP pick smallest wi - branch",
        "solve_two_branches_biggest_wi": r"Solve LP pick biggest wi - branch",
        "primal_branching": r"Primal Rounding - branch",
        "doerr_rr": r"Randomized Rounding",
    }

    def collect_ratio_by_param(all_results):
        d = {}
        for e in all_results:
            p = e["varying_param"]
            r = e.get("ratio_alg_opt", math.nan)
            d.setdefault(p, []).append(r)
        return d

    # Collect all params across all algorithms
    per_alg = {alg: collect_ratio_by_param(res) for alg, res in results_by_alg.items()}
    all_params = sorted(set().union(*[set(d.keys()) for d in per_alg.values()]))

    if not all_params:
        print("No x-values found.")
        return

    plt.figure()

    # Plot each algorithm
    for alg, d in per_alg.items():
        avg = [safe_mean(d.get(p, [])) for p in all_params]
        #err = [safe_ci95(d.get(p, [])) for p in all_params]

        plt.errorbar(
            all_params, avg, #yerr=err, capsize=5,
            color=COL.get(alg, "tab:gray"),
            **STYLE.get(alg, dict(linestyle="-", marker="o")),
            label=rf"{label_map.get(alg, alg)}"
        )

    xlabel_map = {
        "n": r"Number of items $n$",
        "k": r"Number of scenarios $k$",
        "p": r"Number of items to select $p$"
    }
    plt.xlabel(xlabel_map.get(var_param, ""))
    plt.ylabel(r"Approximation ratio $\mathrm{{ALG}}/\mathrm{{OPT}}_\mathrm{{IP}}$")

    # # subtitle
    # any_res = next(iter(results_by_alg.values()))
    # p_label = any_res[0].get("p_label", "") if any_res else ""
    # subtitle = (
    #     r"(Average over " + str(num_runs) + r" runs $\mid$ "
    #     + (r"$n$=" + str(fixed_n) + ", " if var_param != "n" and fixed_n is not None else "")
    #     + (r"$p$=" + p_label + ", " if var_param != "p" and p_label else "")
    #     + (r"$k$=" + str(fixed_k) + ", " if var_param != "k" and fixed_k is not None else "")
    #     + r"cost range: [1, " + str(c_range) + "])"
    # )
    #plt.title(subtitle)

    plt.xticks(
        all_params,
        rotation=45,
        ha='right',
        rotation_mode='anchor'  # verhindert das „Wandern“ der Ticks
    )
    plt.gcf().set_size_inches(16, 6) #plt.gcf().set_size_inches(12, 6)
    plt.tight_layout()

    # def place_legend(var_param):
    #     # (x,y) are in axes coordinates: (0,0)=bottom-left, (1,1)=top-right
    #     if var_param == "n":
    #         loc = "lower right"
    #         anchor = (0.98, 0.12)
    #     elif var_param == "k":
    #         loc = "upper right"
    #         anchor = (0.98, 0.63)
    #     elif var_param == "p":
    #         loc = "upper right"
    #         anchor = (0.98, 0.98)
    #     else:
    #         loc = "best"
    #         anchor = None
    #
    #     if anchor is None:
    #         plt.legend(loc=loc, framealpha=0.8)
    #     else:
    #         plt.legend(loc=loc, bbox_to_anchor=anchor, framealpha=0.8)
    # place_legend(var_param)
    def place_legend(var_param=None):
        # Legend outside on the right
        plt.legend(
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),  # right of axes, vertically centered
            framealpha=0.8
        )
        # make room for legend
        plt.gcf().subplots_adjust(right=0.78)

    place_legend(var_param)

    plt.tight_layout()
    plt.savefig(output_plot, bbox_inches="tight")

    plt.close()

    print(f"Plot saved to {output_plot}")


def plot_guarantee_comp(results_by_alg, num_runs, var_param, fixed_n=None, fixed_k=None, c_range=None,
                        output_dir="results"):
    """
    Compare approximation guarantees (stored as 'approximation_guarantee') across selected algorithms.
    Plots average ± 95% CI over runs, grouped by varying_param.
    """
    param_suffix = f"_{var_param}" if var_param in {"n", "k", "p"} else ""
    output_plot = f"{output_dir}/plot_guarantee_comparison{param_suffix}.png"

    if not results_by_alg:
        print("No results to compare.")
        return

    # only these algorithms
    allowed = {
        "opt_w",
        "opt_w_remember",
        "opt_w_n_remember",
        "opt_w_n_remember_rob_obj",
        "solve_two_branches_smallest_wi",
        "solve_two_branches_biggest_wi",
    }
    results_by_alg = {alg: res for alg, res in results_by_alg.items() if alg in allowed}
    if not results_by_alg:
        print("No matching algorithms for guarantee plot.")
        return

    label_map = {
        "opt_w": r"Solve LP select smallest $p$",
        "opt_w_remember": r"Iterative (remember)",
        "opt_w_n_remember": r"$n$-probe iterative (remember)",
        "opt_w_n_remember_rob_obj": r"Solve LP n times each step (remember, min robust obj)",
        "solve_two_branches_smallest_wi": r"Branch on smallest $w_i$",
        "solve_two_branches_biggest_wi": r"Branch on biggest $w_i$",
    }

    def collect_guarantee_by_param(all_results):
        d = {}
        for e in all_results:
            pval = e["varying_param"]
            g = e.get("approximation_guarantee", math.nan)
            d.setdefault(pval, []).append(g)
        return d

    per_alg = {alg: collect_guarantee_by_param(res) for alg, res in results_by_alg.items()}
    all_params = sorted(set().union(*[set(d.keys()) for d in per_alg.values()]))
    if not all_params:
        print("No x-values found.")
        return

    plt.figure()

    # plot each algorithm with avg ± 95% CI
    for alg, d in per_alg.items():
        avg = [safe_mean(d.get(p, [])) for p in all_params]
        err = [safe_ci95(d.get(p, [])) for p in all_params]

        plt.errorbar(
            all_params, avg, yerr=err, capsize=5,
            color=COL.get(alg, "tab:gray"),
            **STYLE.get(alg, dict(linestyle="-", marker="o")),
            label=rf"{label_map.get(alg, alg)} (Ø $\pm$ 95\% CI)"
        )

    xlabel_map = {
        "n": r"Number of items $n$",
        "k": r"Number of scenarios $k$",
        "p": r"Number of items to select $p$"
    }
    plt.xlabel(xlabel_map.get(var_param, ""))
    plt.ylabel(r"Approximation guarantee $1/t$")

    # subtitle like your other plots
    # try to reuse p_label if present
    any_res = next(iter(results_by_alg.values()))
    p_label = any_res[0].get("p_label", "") if any_res else ""
    subtitle = (
        r"(Average over " + str(num_runs) + r" runs $\mid$ "
        + (r"$n$=" + str(fixed_n) + ", " if var_param != "n" and fixed_n is not None else "")
        + (r"$p$=" + p_label + ", " if var_param != "p" and p_label else "")
        + (r"$k$=" + str(fixed_k) + ", " if var_param != "k" and fixed_k is not None else "")
        + r"cost range: [1, " + str(c_range) + "])"
    )
    plt.title(subtitle)

    plt.xticks(all_params, rotation=45, ha='right', rotation_mode='anchor')
    plt.gcf().set_size_inches(16, 6) #plt.gcf().set_size_inches(12, 6)
    plt.tight_layout()

    # legend placement same logic as before
    # def place_legend(var_param):
    #     if var_param == "n":
    #         loc = "upper left"
    #         anchor = (0.02, 0.98)
    #     elif var_param == "k":
    #         loc = "upper left"
    #         anchor = (0.02, 0.98)
    #     elif var_param == "p":
    #         loc = "upper left"
    #         anchor = (0.02, 0.98)
    #     else:
    #         loc = "best"
    #         anchor = None
    #
    #     if anchor is None:
    #         plt.legend(loc=loc, framealpha=0.8)
    #     else:
    #         plt.legend(loc=loc, bbox_to_anchor=anchor, framealpha=0.8)
    #
    # place_legend(var_param)

    def place_legend():
        # Legend outside on the right
        plt.legend(
            loc="center left",
            bbox_to_anchor=(1.02, 0.5),  # slightly outside right border
            borderaxespad=0.0,
            framealpha=0.8
        )

        # make room for legend
        plt.gcf().subplots_adjust(right=0.75)

    place_legend()

    plt.tight_layout()
    plt.savefig(output_plot, bbox_inches="tight")
    plt.close()
    print(f"Plot saved to {output_plot}")

def plot_branch_guarantees(all_results, num_runs, var_param,
                           fixed_n=None, fixed_k=None, c_range=None,
                           output_dir="results"):
    """
    Plottet für einen Branch-Algorithmus (smallest/biggest w_i)
    die durchschnittliche Garantie 1/t:
      - Baseline-LP: 1 / t0
      - Gewählter Branch: 1 / t_chosen
    über den variierenden Parameter (n, k oder p).
    """
    if not all_results:
        print("No results to plot in plot_branch_guarantees.")
        return

    param_suffix = f"_{var_param}" if var_param in {"n", "k", "p"} else ""
    output_plot = f"{output_dir}/plot_branch_guarantees{param_suffix}.png"

    import math
    param_to_G0 = {}
    param_to_Gchosen = {}
    for entry in all_results:
        param = entry["varying_param"]
        t0 = float(entry["t0"])
        t_chosen = float(entry["t_chosen"])
        G0 = (1.0 / t0) if t0 > 0 else math.nan
        Gc = (1.0 / t_chosen) if t_chosen > 0 else math.nan
        param_to_G0.setdefault(param, []).append(G0)
        param_to_Gchosen.setdefault(param, []).append(Gc)

    param_values = sorted(param_to_G0.keys())
    if not param_values:
        print("No x-values found in plot_branch_guarantees.")
        return

    avg_G0 = [safe_mean(param_to_G0[p]) for p in param_values]
    ci_G0  = [safe_ci95(param_to_G0[p]) for p in param_values]
    avg_Gc = [safe_mean(param_to_Gchosen[p]) for p in param_values]
    ci_Gc  = [safe_ci95(param_to_Gchosen[p]) for p in param_values]

    alg_key = all_results[0].get("algorithm", "")
    nice_name_map = {
        "solve_two_branches_smallest_wi": r"Branch on smallest $w_i$",
        "solve_two_branches_biggest_wi":  r"Branch on biggest $w_i$",
    }
    nice_name = nice_name_map.get(alg_key, alg_key)

    fig = plt.figure()

    plt.errorbar(
        param_values, avg_G0, yerr=ci_G0, capsize=5,
        linestyle="-", marker="o",
        label=rf"{nice_name}: baseline guarantee $1/t_0$"
    )

    plt.errorbar(
        param_values, avg_Gc, yerr=ci_Gc, capsize=5,
        linestyle="--", marker="s",
        label=rf"{nice_name}: chosen branch guarantee $1/t_\mathrm{{chosen}}$"
    )

    xlabel_map = {
        "n": r"Number of items $n$",
        "k": r"Number of scenarios $k$",
        "p": r"Number of items to select $p$",
    }
    plt.xlabel(xlabel_map.get(var_param, ""))
    plt.ylabel(r"Average guarantee $1/t$")

    p_label = all_results[0].get("p_label", "") if all_results else ""
    subtitle = (
        r"(Average over " + str(num_runs) + r" runs $\mid$ "
        + (r"$n$=" + str(fixed_n) + ", " if var_param != "n" and fixed_n is not None else "")
        + (r"$p$=" + p_label + ", " if var_param != "p" and p_label else "")
        + (r"$k$=" + str(fixed_k) + ", " if var_param != "k" and fixed_k is not None else "")
        + r"cost range: [1, " + str(c_range) + "])"
    )
    plt.title(subtitle)

    plt.xticks(param_values)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_plot, bbox_inches="tight")
    plt.close(fig)
    print(f"Branch guarantee plot saved to {output_plot}")

def plot_branch_perf_vs_guarantee(results_by_alg, num_runs, var_param,
                                  fixed_n=None, fixed_k=None, c_range=None,
                                  output_dir="results"):
    allowed = {"solve_two_branches_smallest_wi", "solve_two_branches_biggest_wi", "primal_branching"}
    filtered = {alg: res for alg, res in results_by_alg.items() if alg in allowed}
    if not filtered:
        print("No branch algorithms found for plot_branch_perf_vs_guarantee.")
        return

    xlabel_map = {
        "n": r"Number of items $n$",
        "k": r"Number of scenarios $k$",
        "p": r"Number of items to select $p$"
    }

    label_map = {
        "solve_two_branches_smallest_wi": r"Branch on smallest $w_i$",
        "solve_two_branches_biggest_wi": r"Branch on biggest $w_i$",
        "primal_branching": r"Primal Rounding - branch",
    }

    for alg, all_results in filtered.items():
        param_suffix = f"_{var_param}" if var_param in {"n", "k", "p"} else ""
        output_plot = f"{output_dir}/plot_branch_perf_and_guarantee_{alg}{param_suffix}.png"

        per_param_G = {}
        per_param_R = {}
        for entry in all_results:
            param = entry["varying_param"]
            ratio = entry.get("ratio_alg_opt", math.nan)
            G = entry.get("approximation_guarantee", math.nan)
            per_param_G.setdefault(param, []).append(G)
            per_param_R.setdefault(param, []).append(ratio)

        param_values = sorted(per_param_G.keys())
        if not param_values:
            print(f"No x-values for {alg} in plot_branch_perf_vs_guarantee.")
            continue

        avg_G = [safe_mean(per_param_G[p]) for p in param_values]
        ci_G  = [safe_ci95(per_param_G[p]) for p in param_values]
        avg_R = [safe_mean(per_param_R[p]) for p in param_values]
        ci_R  = [safe_ci95(per_param_R[p]) for p in param_values]

        fig = plt.figure()
        color = COL.get(alg, "black")

        plt.errorbar(
            param_values, avg_G, yerr=ci_G, capsize=5,
            linestyle="-", marker="o",
            color=color,
            label=rf"{label_map.get(alg, alg)} guarantee $1/t$ (Ø $\pm$ 95\% CI)"
        )

        plt.errorbar(
            param_values, avg_R, yerr=ci_R, capsize=5,
            linestyle="--", marker="s",
            color=color,
            label=rf"{label_map.get(alg, alg)} performance $\mathrm{{ALG}}/\mathrm{{OPT}}_\mathrm{{IP}}$ (Ø $\pm$ 95\% CI)"
        )

        plt.xlabel(xlabel_map.get(var_param, ""))
        plt.ylabel(r"Approximation guarantee / ratio")

        any_res = all_results
        p_label = any_res[0].get("p_label", "") if any_res else ""
        subtitle = (
            r"(Average over " + str(num_runs) + r" runs $\mid$ "
            + (r"$n$=" + str(fixed_n) + ", " if var_param != "n" and fixed_n is not None else "")
            + (r"$p$=" + p_label + ", " if var_param != "p" and p_label else "")
            + (r"$k$=" + str(fixed_k) + ", " if var_param != "k" and fixed_k is not None else "")
            + r"cost range: [1, " + str(c_range) + "])"
        )
        plt.title(subtitle)
        plt.xticks(param_values, rotation=45, ha='right', rotation_mode='anchor')
        plt.legend()
        plt.tight_layout()
        plt.savefig(output_plot, bbox_inches="tight")
        plt.close(fig)
        print(f"Branch perf-and-guarantee plot saved to {output_plot}")

